name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [ 'none', 'patch_runtime' ]
        version: [ '1.12', '1.13', '1.14', '1.15', '1.16' ]
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v2
    - run: ./patch_runtime.sh
      if: matrix.version == 'patch_runtime'
    - run: go mod tidy && git diff --exit-code go.mod go.sum
    - run: go vet -tags ${{ matrix.tags }} ./...
    - run: go test -tags ${{ matrix.tags }}
    - run: go build -tags ${{ matrix.tags }},example ./examples/*
